#### Exploring NYC Public School Test Result Scores

**Source:** Datacamp</br>
**Link:** https://app.datacamp.com/learn/projects/exploring_nyc_public_school_test_result_scores/guided/Python

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [1]:
import pandas as pd

In [2]:
schools = pd.read_csv("schools.csv")
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

**Question 1: Which NYC schools have the best math results?**

In [3]:
# Step 1: Find the schools with an average_math score that is at least 80% of 800 (max score)
schools[(schools['average_math'] >= (0.8 * 800))]
schools.sample(10)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
137,Knowledge and Power Preparatory Academy Intern...,Bronx,X435,408,417,404,66.7
296,High School for Global Citizenship,Brooklyn,K440,377,386,375,61.9
189,Bronx Guild,Bronx,X450,365,393,357,41.3
212,Frank Sinatra School of the Arts High School,Queens,Q570,536,543,543,89.5
299,High School for Youth and Community Developmen...,Brooklyn,K465,360,382,359,63.2
10,Pace High School,Manhattan,M131,430,435,427,87.8
277,Secondary School for Law,Brooklyn,K460,420,424,414,74.7
326,World Journalism Preparatory (College Board),Queens,Q025,484,491,487,89.2
351,Robert H. Goddard High School of Communication...,Queens,Q202,426,435,424,85.1
233,Brooklyn Community High School of Communicatio...,Brooklyn,K117,358,386,380,51.7

In [4]:
# Step 2: Only display the school_name and the average_math score
schools[(schools['average_math'] >= (0.8 * 800))][['school_name', 'average_math']]

                                           school_name  average_math
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641
68   High School for Mathematics, Science, and Engi...           683
88                              Stuyvesant High School           754
93                 Staten Island Technical High School           711
170                       Bronx High School of Science           714
174  High School of American Studies at Lehman College           669
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
365  Queens High School for the Sciences at York Co...           701

In [5]:
# Step 3: Create a new dataframe for this data, and sort it by "average_math" in descending order.

best_math_schools = schools[(schools['average_math'] >= 640)][['school_name', 'average_math']]
best_math_schools = best_math_schools.sort_values('average_math', ascending=False) # RMB to reassign, else the change does not persist
best_math_schools.head()

# Alternative method that combines step 1, 2 and 3
# best_math_schools = schools[schools["average_math"] >= 640][["school_name", "average_math"]].sort_values("average_math", ascending=False)

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683

**Question 2: What are the top 10 performing schools based on the combined SAT scores?**

In [6]:
#Step 1: Create a duplicate of the original dataframe, and create a new column called 'total_sat'
schools_duplicate = schools
schools_duplicate['total_SAT'] = schools_duplicate['average_math'] + schools_duplicate['average_reading'] + schools_duplicate['average_writing']
schools_duplicate.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197

In [7]:
top_10_schools = schools_duplicate[['school_name', 'total_SAT']].sort_values('total_SAT', ascending=False).head(10)
top_10_schools.head()

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981

**Question 3: Which single borough has the largest standard deviation in the combined SAT score?**

In [8]:
# Note: The function agg calculates the statistics based on the coloumn 'total_SAT'
# .agg(["count", "mean", "std"]) → calculates:
    # count → number of schools in each borough
    # mean → average SAT score
    # std → standard deviation (how spread out scores are)

boroughs = schools.groupby("borough")["total_SAT"].agg(["count", "mean", "std"]).round(2)

In [9]:
# Filter for max std based on std, note: there can be more than 1 borough with the max std
largest_std_dev = boroughs[boroughs["std"] == boroughs["std"].max()]
largest_std_dev.head()

           count     mean     std
borough
Manhattan     89  1340.13  230.29

In [10]:
# Rename the columns for clarity
largest_std_dev = largest_std_dev.rename(columns={"count": "num_schools", "mean": "average_SAT", "std": "std_SAT"})
largest_std_dev.head()

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29

In [11]:
# Move borough from index to column
largest_std_dev.reset_index(inplace=True)
largest_std_dev.head()

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29